# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('subsetSeqLib_rcpp_hello_world', PACKAGE = 'subsetSeqLib')
}

fastqReader_Open <- function(f) {
    .Call('subsetSeqLib_fastqReader_Open', PACKAGE = 'subsetSeqLib', f)
}

